apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:9AuZa1YrdiZE1N/VkpVxot6+F2BA2ibjz6o/OU/xSkHq008xAa7bSOBOxsvT1oQy3vns/TnuSdExWgYUIS2eoXcNxZLw+7xHEKMVOZAzUrphgdGFnfy/IfDYc2PxWqxJNr4WY1e/82IICG4veUJ48eKmSvYovStpsrLHVWHsfPcEFHUVvwST2fdgky+UNovTRLmCUZVJY987YXGd2sOlMn02afvYMeI+jL3hXWdt3XqPyrtPRGn6/n1PRt8TrSWsjQl8vOLsQwv+xhDFdwlo6njVYZTjEHKh0CO387lO68Ly1TMXnsi5Pvu3rAM=,iv:V0sxnpdeBXEeWSc09RwrhcWZqhKQG9F1qrSo3iIH/Zg=,tag:Yti1vAMI25FTaMMWHS9RYQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1sc0lmje252zcv5fe2j0exc34tcuq4t7pnvspjltwnn099e0qwdqq9lw97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3a1NFd3d4LzRBcTVKb0ZP
            YlE5alFEY2R5NzJTQit5ZlJuSTBZemVwNFFvCjBTVlVNV1ZrSiszMnBmLzkxd0Zm
            WHBXSm9Sc2hrK0hoNmpta0pNRng0b0EKLS0tIFRDZGJtNUN1cGdGZWhTQTJSMzEx
            L2hZNzQ1cFJGL3Q0WVZsMHFiQXRJRjAKyGmUXqaSWXTjUGU0CEylui2tqXBB3/UF
            f31gC1TCUamUO++BqdkSstZSBD66owTHBh3DEnB2f1FqGWqVjPwu4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T20:18:37Z"
    mac: ENC[AES256_GCM,data:J6qP16Q8X47ZKX1nGhVDHOIJXKgi+OxT2LawlDsnDj+C5EmfT6DEbzaCvjCRCQ26cGWVyD23rDejCmVjgmuzZm/ONXJS2Gsp+oNC2u23tjcfQzAMLR5vL0HO9k8FWlU3upe8wjtquIsb0ZK85oErWjUzI/MZAWOKKZ8g03szRMM=,iv:VThH7Um4zY3udh/RW4v+/hgy0AvkAdNadDYbgNDYgSc=,tag:m4EbZSTOSdBTP+btNdu6vQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
