apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:xtNeOmjRrTw=,iv:ZQl25QSgAtCb7lNaCRB6FXwcXqohx8mhTBWdtpOdDlc=,tag:VP/l0YVVWmw/ClCVoBVOow==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:iXVNTv3nkKcbQrCY,iv:iwxrudPBEcNPpvAkARX4FKHuIYf0r5kL5Bvmvzrd3Gw=,tag:dvB3WTRJDcJVy8WCvMONdQ==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1sc0lmje252zcv5fe2j0exc34tcuq4t7pnvspjltwnn099e0qwdqq9lw97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZDh6ZXFPcXhTa2FmY295
            czRQTS9zZHhGMlRMa0VWR0hIWGIwdTBhU0FnCkwrQnI5NDZaSWREMVRmeVltTXkr
            dzJNWENDdEpDMjNnUlJGV2FEb2ZDWFEKLS0tIHpYZ0Z5ZGQ0cEdxVlg5VGxTemQr
            TEwrMWlTNlhGMUx5bnlsS3F5NnBPWncKDM3pgnHWIvOOPs9xFKc7AQNm1rlwnWNh
            4kp+2Hdn19ci6MG8I2Bsm3y2Mw8fPBkKUOvHNbntSnyO5CaS5fYkdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T21:05:28Z"
    mac: ENC[AES256_GCM,data:wI4YWRjVW3RtgS9cq4iXebsIN4iEWk91aIznzXnuts0NMSz1BCMXbxcAXoJ+MnZXFxQMzCBj720iSrJUEajg+NOmQeWs3FXpasrJmzOiw3xqsa20QtdLSEnTV9thR7myRQnET9fGl6i+17iYj2DhlhnhPS4LumTBuYN6IrF8+24=,iv:BE3f/GYNs3GVC0qsdQ6mGoQbdnIfnVZNye8j3aIKQCk=,tag:gZFnx1ypiVB/5Ux2Pzq46A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
