apiVersion: v1
data:
    password: ENC[AES256_GCM,data:V+YEjEtnZT8=,iv:walVGH5KJlcVW91Lm+rLomAqHxRy97ZwUNsLH52GHjI=,tag:YMnDrLKucy5mR+BMfoG4bQ==,type:str]
    user: ENC[AES256_GCM,data:XVu3Rn895NM=,iv:2IiIe93Aihinr5EOOhO7dK7x9Xty4sfCpqj32xWiXwo=,tag:PNDOJoSpsVoqol15NYM55g==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1sc0lmje252zcv5fe2j0exc34tcuq4t7pnvspjltwnn099e0qwdqq9lw97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcGEybStwWUY2eEx6dzVT
            dkxueUtDdUVid2pmS1FMVmFNOUJsbVZhVmxnCkE3LzZwclFSd3Zmd3FSRVFpZHZl
            d3hwZk96UVZTalAyZTNWNC9GUUpKVlUKLS0tIGhkZUNGOWRtSjdaOXlONlVwWEp0
            ZEFWQXpROVNzd1ZlNW5nOHlManppaEUK5BjKCsVTnA/WM/RvcfRM0OS5rNsw1VUv
            UNh00cLJgMH7YklHnXu7mJsTG7WRx9tTZl52BTx6GrV0MvOAMznYMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T16:18:08Z"
    mac: ENC[AES256_GCM,data:pLS+By/VZPqvEm5g4c3/4KPT0HWzM5LMZLP7IXQLl/gGCRzsObKAdQxSi2xhlHFdl3mFVy1aY54CN+JHICzz6UlM4YBrZnQTipof+UwV2tvf3RGHossdMBWu+Uub3KAGFeGVrKZQHmpMFJsOW4o/BoO8PiD38a3sXno3xlghntc=,iv:cU2ZmYMmtsKsvEBfkffxrNtAzfoqxagf03hZn1iY1Sw=,tag:px1r0qhB5U1w5+JgJ8ug7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1