apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      #  Set the security context for the entire pod to 
      # run as www-data user and group (UID and GID 33) 
      # for proper file permissions
      securityContext:
        # www-data group ID for file permissions
        fsGroup: 33 
        # www-data user ID for running processes
        runAsUser: 33 
        # www-data group ID for running processes
        runAsGroup: 33 

      containers:
        - name: linkding
          image: sissbruecker/linkding:1.31.0
          ports:
            - containerPort: 9090

          # Set the security context for the container to prevent privilege escalation
          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
